# Generated by Django 5.2.8 on 2025-11-15 10:55

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.TextField(default=main.models.generate_id, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, upload_to=main.models.achievement_path)),
            ],
        ),
        migrations.CreateModel(
            name='AppAgeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(default='')),
                ('icon', models.ImageField(blank=True, upload_to=main.models.icon_path)),
            ],
        ),
        migrations.CreateModel(
            name='AppDeveloper',
            fields=[
                ('id', models.TextField(default=main.models.generate_id, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('description', models.TextField(default='')),
                ('avatar', models.ImageField(blank=True, upload_to=main.models.app_developer_path)),
            ],
        ),
        migrations.CreateModel(
            name='StoreUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.TextField(default=main.models.generate_id, editable=False, primary_key=True, serialize=False)),
                ('avatar', models.ImageField(blank=True, upload_to=main.models.user_path)),
                ('achievements', models.JSONField(default=list, editable=False)),
                ('estimations', models.JSONField(default=list, editable=False)),
                ('bought_apps', models.JSONField(default=list, editable=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.TextField(default=main.models.generate_id, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, upload_to=main.models.app_path)),
                ('rating', models.FloatField(default=0.0, editable=False)),
                ('estimations_count', models.PositiveBigIntegerField(default=0, editable=False)),
                ('downloads', models.PositiveBigIntegerField(default=0, editable=False)),
                ('views', models.PositiveBigIntegerField(default=0, editable=False)),
                ('size', models.FloatField()),
                ('age_rating', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.appagerating')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.appdeveloper')),
            ],
        ),
        migrations.CreateModel(
            name='AppEstimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimation', models.FloatField()),
                ('published_at', models.DateTimeField()),
                ('content', models.TextField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.app')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppPreviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField()),
                ('source', models.ImageField(default=None, upload_to=main.models.app_preview_image_path)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.app')),
            ],
        ),
        migrations.CreateModel(
            name='AppSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('icon', models.ImageField(blank=True, upload_to=main.models.icon_path)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.appcategory')),
            ],
        ),
        migrations.AddField(
            model_name='app',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.appsubcategory'),
        ),
    ]
