# Generated by Django 5.2.8 on 2025-11-15 09:12

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_appagerating_appcategory_appdeveloper_app_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='icon',
            field=models.ImageField(default=None, upload_to=main.models.app_path),
        ),
        migrations.AlterField(
            model_name='appcategory',
            name='icon',
            field=models.ImageField(default=None, upload_to=main.models.icon_path),
        ),
        migrations.AlterField(
            model_name='appdeveloper',
            name='avatar',
            field=models.ImageField(default=None, upload_to=main.models.app_developer_path),
        ),
        migrations.AlterField(
            model_name='apppreviewimage',
            name='source',
            field=models.ImageField(default=None, upload_to=main.models.app_preview_image_path),
        ),
        migrations.AlterField(
            model_name='appsubcategory',
            name='icon',
            field=models.ImageField(default=None, upload_to=main.models.icon_path),
        ),
    ]
